# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev = suppressevent maximize, class:.* # You'll probably like this.
windowrulev = opaque, title:(.*)(Code)$
windowrulev = opaque, title:(.*)(Brave)$
windowrulev = opaque, title:(.*)(Weather)$
windowrulev = opaque, title:(.*)(Firefox)$
windowrulev = opaque, title:(.*)(RLCraft)$

# Won't really work, cant get the correct name
windowrulev = opaque, title:(.*)(Factorio)$
windowrulev = opaque, title:(.*)(eclipse-java-bin)$

windowrulev = float,class:(clipse)
windowrulev = size 622 652,class:(clipse)

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
